export const districtsList = [
  { id: 1, name: "Bagerhat" },
  { id: 2, name: "Bandarban" },
  { id: 3, name: "Barguna" },
  { id: 4, name: "Barishal" },
  { id: 5, name: "Bhola" },
  { id: 6, name: "Bogura" },
  { id: 7, name: "Brahmanbaria" },
  { id: 8, name: "Chandpur" },
  { id: 9, name: "Chapainawabganj" },
  { id: 10, name: "Chattogram" },
  { id: 11, name: "Chuadanga" },
  { id: 12, name: "Cox's Bazar" },
  { id: 13, name: "Cumilla" },
  { id: 14, name: "Dhaka" },
  { id: 15, name: "Dinajpur" },
  { id: 16, name: "Faridpur" },
  { id: 17, name: "Feni" },
  { id: 18, name: "Gaibandha" },
  { id: 19, name: "Gazipur" },
  { id: 20, name: "Gopalganj" },
  { id: 21, name: "Habiganj" },
  { id: 22, name: "Jamalpur" },
  { id: 23, name: "Jashore" },
  { id: 24, name: "Jhenaidah" },
  { id: 25, name: "Joypurhat" },
  { id: 26, name: "Khagrachari" },
  { id: 27, name: "Khulna" },
  { id: 28, name: "Kishoreganj" },
  { id: 29, name: "Kurigram" },
  { id: 30, name: "Kushtia" },
  { id: 31, name: "Lakshmipur" },
  { id: 32, name: "Lalmonirhat" },
  { id: 33, name: "Magura" },
  { id: 34, name: "Madaripur" },
  { id: 35, name: "Manikganj" },
  { id: 36, name: "Meherpur" },
  { id: 37, name: "Moulvibazar" },
  { id: 38, name: "Munshiganj" },
  { id: 39, name: "Mymensingh" },
  { id: 40, name: "Naogaon" },
  { id: 41, name: "Narail" },
  { id: 42, name: "Narayanganj" },
  { id: 43, name: "Narsingdi" },
  { id: 44, name: "Natore" },
  { id: 45, name: "Netrokona" },
  { id: 46, name: "Nilphamari" },
  { id: 47, name: "Noakhali" },
  { id: 48, name: "Pabna" },
  { id: 49, name: "Panchagarh" },
  { id: 50, name: "Patuakhali" },
  { id: 51, name: "Pirojpur" },
  { id: 52, name: "Rajbari" },
  { id: 53, name: "Rajshahi" },
  { id: 54, name: "Rangamati" },
  { id: 55, name: "Rangpur" },
  { id: 56, name: "Satkhira" },
  { id: 57, name: "Shariatpur" },
  { id: 58, name: "Sherpur" },
  { id: 59, name: "Sirajganj" },
  { id: 60, name: "Sunamganj" },
  { id: 61, name: "Sylhet" },
  { id: 62, name: "Tangail" },
  { id: 63, name: "Thakurgaon" }
];

export const adoptionFormControls = [
  {
    name: "breed",
    label: "Breed",
    placeholder: "Husky, Persian etc..",
    componentType: "select",
    options: [
      {
        petType: "cat",
        breed: [
          "Regular",
          "Persian",
          "Siamese",
          "British Shorthair",
          "Scottish Fold",
          "Mixed",
          "Others",
        ],
      },
      {
        petType: "dog",
        breed: [
          "Regular",
          "German Shepherd",
          "Labardor Retriever",
          "Bulldog",
          "Chihuahua",
          "Huskey",
          "Mixed",
          "Others",
        ],
      },
      {
        petType: "bird",
        breed: [
          "Parrot",
          "Oriental magpie-robin",
          "Kingfisher",
          "Cuckoos",
          "Myna",
          "Others",
        ],
      },
      {
        petType: "rabbit",
        breed: ["Dutch Lops", "Lionheads", "Mini Rex", "Others"],
      },
    ],
  },
  {
    name: "region",
    label: "Region",
    placeholder: "Enter your district/city",
    componentType: "select",
    options: districtsList,
  },
];

export const adoptionRequestFormControls = [
  {
    name: "animalType",
    label: "Pet Type",
    placeholder: "Cat, Dog, Parrot etc....",
    componentType: "input",
    type: "text",
  },
  {
    name: "breed",
    label: "Breed",
    placeholder: "Scottish fold, Huskey etc...",
    componentType: "input",
    type: "text",
  },
  {
    name: "name",
    label: "Name",
  },
];

export const petTypeBreeds = [
  {
    petType: "cat",
    breed: [
      "Regular",
      "Persian",
      "Siamese",
      "British Shorthair",
      "Scottish Fold",
      "Mixed",
      "Others",
    ],
  },
  {
    petType: "dog",
    breed: [
      "Regular",
      "German Shepherd",
      "Labardor Retriever",
      "Bulldog",
      "Chihuahua",
      "Huskey",
      "Mixed",
      "Others",
    ],
  },
  {
    petType: "bird",
    breed: [
      "Parrot",
      "Oriental magpie-robin",
      "Kingfisher",
      "Cuckoos",
      "Myna",
      "Others",
    ],
  },
  {
    petType: "rabbit",
    breed: ["Dutch Lops", "Lionheads", "Mini Rex", "Others"],
  },
];




